OmarCrm/CRM/urls.py
from django.urls import path 
from . import views 
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

app_name = 'CRM'

urlpatterns = [
    path('',RedirectView.as_view(url='accounts/login')),
    path('',views.test,name='home'),
    path('NewCustomerInfo',views.NewCustomerInfo.as_view() , name='NewCustomerInfo'),
    path('NewComment/<int:pk>',views.NewComment.as_view() , name='NewComment'),
    path('NewProject',views.NewProject.as_view() , name='NewProject'),
    path('updateProject/<int:pk>',views.updateProject.as_view() , name='updateProject'),
    path('AssignPoject',views.AssignPojectView.as_view() , name='AssignPoject'),
    path('customerList',views.customerList , name='customerList'),
    path('UserCheckProject',views.UserCheckProject,name='UserCheckProject'),
    path('signUp',views.signUpView.as_view(),name='signUp'),
    path('customerProfile/<int:pk>',views.customerProfile,name='customerProfile'),
    path('updateCustomerProfile/<int:pk>',views.updateCustomerProfile.as_view(),name='updateCustomerProfile'),
    path('ProjectsList',views.ProjectsList,name='ProjectsList'),
    path('ProjectsHistoryList',views.ProjectsHistoryList,name='ProjectsHistoryList'),
    path('testView',views.testView.as_view(),name='testView'),
    path('NewPayment',views.NewPaymentView.as_view(),name='NewPayment'),
    path('PaymentHitoryList',views.PaymentHistory,name='PaymentHitoryList'),
    path('deletePayment/<int:pk>',views.deletePayment.as_view(),name='deletePayment'),
    path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('financeOpenBalance', views.financeBalance ,name='financeOpenBalance'),
    path('financeClosedBalance', views.financeBalance ,name='financeClosedBalance'),
    path('CustomerBalance/<int:pk>', views.CustomerAccountBalance ,name='CustomerBalance'),
    path('PRMonthly', views.projectMonthlyReport ,name='PRMonthly'),
    path('testView2', views.testView2 ,name='testView2'),



  

]

OmarCrm/OmarCrm/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CRM.urls')),
    path('accounts/',include('django.contrib.auth.urls'))
]

OmarCrm/CRM/forms.py
from django import forms
from . models import CustomerInfoModel , ProjectInfoModel , assignProjectModel, commentsModel , paymentsModel
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.admin import widgets
from django.contrib.admin.widgets import AdminDateWidget



### Authentaion 

#####



#####

class customerInfoForm(forms.ModelForm):
    class Meta:
        model = CustomerInfoModel
        fields = ('customerName','country','address','mobileNumber','workNumber','email','GD1','userLogin')

        GD1 = forms.DateField(widget=AdminDateWidget())

        widgets = {
            'customerName' : forms.TextInput(attrs={'class':'form-control'} ),
            'country' : forms.Select(attrs={'class':'form-control'} ),
            'address' : forms.TextInput(attrs={'class':'form-control'} ),
            'mobileNumber' : forms.NumberInput(attrs={'class':'form-control'} ),
            'workNumber' : forms.NumberInput(attrs={'class':'form-control'} ),
            'email' : forms.EmailInput(attrs={'class':'form-control'} ),
            'GD1' : forms.DateInput(format=('%Y-%m-%d'),attrs={'class':'form-control' , 'placeholder':'yyyy-mm-dd (2025-07-28)'} ),
            #'GD1' : forms.DateInput(format='%d/%m/%Y'),
            'userLogin' : forms.Select(attrs={'class':'form-control'})
        }

        labels = {
            'customerName' : 'Customer Name',
            'mobileNumber' : 'Mobile Number',
            'workNumber' : 'Work Number',
            'GD1' : 'Contact Date'
        }

class projectInfoForm(forms.ModelForm):
    class Meta:
        model = ProjectInfoModel
        fields = ('projectName','projectDesc','startDate','endDate','price','active')

        widgets = {
            'projectName' : forms.TextInput(attrs={'class':'form-control'} ),
            'projectDesc' : forms.Textarea(attrs={'class':'form-control'} ),
            'startDate' : forms.DateInput(format=('%Y-%m-%d'),attrs={'class':'form-control' , 'placeholder':'yyyy-mm-dd (2025-07-28)'} ),
            'endDate' : forms.DateInput(format=('%Y-%m-%d'),attrs={'class':'form-control' , 'placeholder':'yyyy-mm-dd (2025-07-28)'} ),
            'price' : forms.NumberInput(attrs={'class':'form-control'}),
        }

        labels = {
            'projectName' : 'Project Name',
            'projectDesc' : 'Project Desc',
            'startDate' : 'Start Date',
            'endDate' : 'End Date',
            'price' : 'Price',
            'active' : 'Acitve',
        }

class assignProjectForm(forms.ModelForm):
    class Meta:
        model = assignProjectModel
        fields = ('customerId','projectId','assignDate')

        widgets = {
            'customerId' : forms.Select(attrs={'class':'form-control'} ),
            'projectId' : forms.Select(attrs={'class':'form-control'} ),
            'assignDate' : forms.DateInput(format=('%Y-%m-%d'),attrs={'class':'form-control' , 'placeholder':'yyyy-mm-dd (2025-07-28)'} ),
            'userLogin' : forms.Select(attrs={'class':'form-control'} ),            
            'createdBy' : forms.Select(attrs={'class':'form-control'} ),            
        }

        labels = {
            'customerId' : 'Customer Name',
            'projectId' : 'Project Desc',
            'assignDate' : 'Start Date',
            'userLogin' : 'User Name',
            'createdBy' : 'createdBy Name',
        }

            

class newCommentForm(forms.ModelForm):
    class Meta:
        model = commentsModel
        fields = ('projectId','comment')

        widgets = {
            'projectId' : forms.Select(attrs={'class':'form-control' , 'hidden': 'True'} ),
            'comment' : forms.Textarea(attrs={'class':'form-control'} ),            
        }

        labels = {
            'projectId' : '',
            'comment' : 'Comment',
        }


class paymentsForm(forms.ModelForm):
    class Meta:
        model = paymentsModel
        fields = ('customerId','paymentRef','transactionDate','paymentType','paymentAmount','Currency')

        widgets = {
            'customerId' : forms.Select(attrs={'class':'form-control'} ),
            'paymentRef' : forms.TextInput(attrs={'class':'form-control'} ),
            'transactionDate' : forms.DateInput(format=('%Y-%m-%d'),attrs={'class':'form-control' , 'placeholder':'yyyy-mm-dd (2025-07-28)'} ),
            'paymentType' : forms.Select(attrs={'class':'form-control'} ),            
            'Currency' : forms.Select(attrs={'class':'form-control'} ),    
            'paymentAmount' : forms.NumberInput(attrs={'class':'form-control'} ),    

                    
        }

        labels = {
            'customerId' : 'Customer Name',
            'paymentRef' : 'Payment Desc',
            'transactionDate' : 'Transaction Date',
            'paymentType' : 'Payment Type',
            'Currency' : 'Currency',
            'paymentAmount' : 'Amount',
        }

OmarCrm/CRM/views.py
from importlib.resources import path
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView , list , ListView , UpdateView , DeleteView
from . models import CustomerInfoModel, assignProjectModel , ProjectInfoModel , commentsModel, paymentsModel , testModel , customerPaymentAccount
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin 
from . forms import customerInfoForm, newCommentForm , projectInfoForm , assignProjectForm , paymentsForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models import Count , Max , F , Min , Q , Sum 
from django.db.models.functions import TruncMonth , TruncYear

### Authintaion :

class signUpView(LoginRequiredMixin,CreateView):
    form_class = UserCreationForm    
    success_url = reverse_lazy('login')
    template_name = 'CRM/signUp.html'

#####

# Create your views here.

def test(request):
    x = 'basel'
    return render(request,'CRM/index.html',{'x':x})

### Create New :

class NewCustomerInfo(LoginRequiredMixin,CreateView):
    template_name = 'CRM/NewCustomer.html'
    form_class = customerInfoForm
    model = CustomerInfoModel
    success_url = '/customerList'

    def form_valid(self, form):
        form.instance.createdBy = self.request.user
        return super().form_valid(form)

class NewProject(LoginRequiredMixin,CreateView):
    template_name = 'CRM/NewProject.html'
    form_class = projectInfoForm
    model = ProjectInfoModel
    success_url = '/customerList'

    def form_valid(self, form):
        form.instance.createdBy = self.request.user
        return super().form_valid(form)

class NewComment(LoginRequiredMixin,CreateView):
    template_name = 'CRM/NewComment.html'
    form_class = newCommentForm
    model = commentsModel
    #success_url = '/customerList'

    def form_valid(self, form):
        form.instance.createdBy = self.request.user
        return super().form_valid(form)

    ## default Value for NewComment
    def get_initial(self):
        projectId = get_object_or_404(ProjectInfoModel, pk=self.kwargs['pk'])


        return {
        'projectId': projectId,
        }  

    def get_context_data(self, **kwargs):
       context = super(NewComment, self).get_context_data(**kwargs)
       context['queryset'] = ProjectInfoModel.objects.filter(pk= self.kwargs['pk'])
       context['CommentList'] = commentsModel.objects.filter(projectId = self.kwargs['pk']).order_by('-commentDate')

       print(context)

       return context

    def get_success_url(self):
       return reverse_lazy('CRM:NewComment' , kwargs={'pk': self.kwargs['pk']})
  
class NewPaymentView(LoginRequiredMixin,CreateView):
    template_name = 'CRM/NewPayment.html'
    form_class = paymentsForm
    model = paymentsModel
    success_url = '/PaymentHitoryList'

    def form_valid(self, form):
        form.instance.createdBy = self.request.user
        return super().form_valid(form)


#### end Create New 

## update views :

class updateProject(LoginRequiredMixin,UpdateView):
    template_name = 'CRM/NewProject.html'
    form_class = projectInfoForm
    model = ProjectInfoModel
    success_url = '/ProjectsList'

class testView(LoginRequiredMixin,CreateView):
    template_name = 'CRM/ZTestView.html'
    #form_class = projectInfoForm
    fields = ('customerIdt',)
    model = testModel
    success_url = '/testView'

class updateCustomerProfile(LoginRequiredMixin,UpdateView):
    template_name = 'CRM/customerProfileUpdate.html'
    form_class = customerInfoForm
    #fields = ['customerName']
    model = CustomerInfoModel
    success_url = '/customerList'

### Assign Project :

class AssignPojectView(LoginRequiredMixin,CreateView):
    template_name = 'CRM/AssignProject.html'
    form_class = assignProjectForm

    model = assignProjectModel
    success_url = '/customerList'

    def get_form(self, *args, **kwargs):
        form = super(AssignPojectView, self).get_form(*args, **kwargs)
        filter = assignProjectModel.objects.values('projectId_id')
        OpenProject = ProjectInfoModel.objects.exclude(projectId__in = filter)
        form.fields['projectId'].queryset = ProjectInfoModel.objects.filter(projectId__in = OpenProject)
        return form

    def form_valid(self, form):
        form.instance.createdBy = self.request.user
        return super().form_valid(form)

### End Assign Project 

#### Deletes
#################

class deletePayment(LoginRequiredMixin,DeleteView):
    #template_name = 'CRM/NewPayment.html'
    model = paymentsModel
    success_url = '/PaymentHitoryList'


## Customer Profile 
@login_required
def customerProfile(request,pk):
    profile = CustomerInfoModel.objects.get(customerId = pk)

    context = {'profile':profile}
    return render(request,'CRM/CustomerProfile.html',context)

## List
@login_required
def customerList(request):
    customerListQuery = CustomerInfoModel.objects.all().filter(active = True)

    context = {'customerListQuery':customerListQuery}

    return render(request,'CRM/customerList.html',context)

@login_required
def ProjectsList(request):
    projectListQuery = assignProjectModel.objects.select_related('projectId_id').values_list('projectId__projectId','projectId__projectName','customerId__customerName','projectId__startDate','projectId__endDate','projectId__price','projectId__active','projectId__createdBy__username','userLogin').filter(projectId__active=True).order_by('-projectId_id')
    context = {'projectListQuery':projectListQuery}

    return render(request,'CRM/projectList.html',context)


@login_required
def ProjectsHistoryList(request):
    projectListQuery = assignProjectModel.objects.select_related('projectId_id').values_list('projectId__projectId','projectId__projectName','customerId__customerName','projectId__startDate','projectId__endDate','projectId__price','projectId__active','projectId__createdBy__username','userLogin').filter(projectId__active=False).order_by('-projectId_id')

    context = {'projectListQuery':projectListQuery}
    return render(request,'CRM/projectHistoryList.html',context)


@login_required
def PaymentHistory(request):
    PyamentHitoryList = paymentsModel.objects.all().order_by('-transactionId')

    context = {'PyamentHitoryList':PyamentHitoryList}
    return render(request,'CRM/PaymentHistoryList.html',context)

## By User itself:
@login_required
def UserCheckProject(request):

    loginUser = User.objects.filter(username = request.user)

    try:
        customerProfile = CustomerInfoModel.objects.filter(userLogin =  loginUser[0])
    except Exception as e:
        customerProfile = ''

    try:
        q1 = assignProjectModel.objects.filter(userLogin = request.user)
    except Exception as e:
        q1 = 'NO Projects'

    try:
        CustomerIDFilter = q1.values_list('customerId')[0]
    except Exception as e:
        CustomerIDFilter = 'NO Projects'
    try:
        CustomerProjects = assignProjectModel.objects.values('projectId__projectName','assignDate','projectId__price','projectId__active','projectId__endDate').filter(customerId = CustomerIDFilter)
    except Exception as e:
        CustomerProjects = ''

    try:
        CustomerPayment = paymentsModel.objects.values('customerId__customerName','transactionDate','paymentType','paymentAmount','Currency').filter(customerId = CustomerIDFilter).order_by('-transactionDate')
    except Exception as e:
        CustomerPayment = ''

    context = {
     'q1':q1 ,
     'CustomerIDFilter':CustomerIDFilter,
     'CustomerProjects':CustomerProjects,
     'customerProfile':customerProfile,
     'loginUser' : loginUser,
     'CustomerPayment' : CustomerPayment
     }

    return render(request,'CRM/Profile.html',context)



#### Reports :
## ACcounting Open Balance 

def financeBalance (request):
    
    # Open
    SOA_OpenBalance = customerPaymentAccount.objects.values('customerId','customerName').annotate(totalCredit = Sum('credit') , totalDebit = Sum('debit') , openBalance = F('totalCredit')-F('totalDebit')).filter(openBalance__gt = 0).order_by('-openBalance')

    #Closed
    SOA_ClosedBalance = customerPaymentAccount.objects.values('customerId','customerName').annotate(totalCredit = Sum('credit') , totalDebit = Sum('debit') , openBalance = F('totalCredit')-F('totalDebit')).filter(openBalance = 0).order_by('-customerId')

    context = {'SOA_OpenBalance':SOA_OpenBalance,'SOA_ClosedBalance':SOA_ClosedBalance}

    return render(request,'CRM/financeOpenBalance.html',context)

def CustomerAccountBalance (request,pk):
    Soa_Customer = customerPaymentAccount.objects.values('customerId','customerName').annotate(totalCredit = Sum('credit') , totalDebit = Sum('debit') , openBalance = F('totalCredit')-F('totalDebit')).filter(customerId = pk)

    SoaDtl_Customer = customerPaymentAccount.objects.all().filter(customerId = pk)


    context = {'Soa_Customer':Soa_Customer,'SoaDtl_Customer':SoaDtl_Customer}

    return render(request,'CRM/financeCustomerBalance.html',context)

## Total Projects : 
def projectMonthlyReport (request):

    if request.method == 'POST':
        yearFilter = request.POST['yearFilter']   
        projectListQuery = customerPaymentAccount.objects.values(year = TruncYear('transactionDate') , month = TruncMonth('transactionDate')).annotate(TDebit = Sum('debit') ,TCredit = Sum('credit') , TCount = Count('credit')).filter(transactionDate__year = yearFilter).order_by('-month')

        context = {'projectListQuery':projectListQuery}
        return render(request,'CRM/MonthlyReport.html',context)
    else:

OmarCrm/CRM/templates/CRM/MonthlyReport.html
{% include 'CRM/base.html' %}
{% include 'CRM/navbar.html' %}
{% load humanize %}

{% block content %}

<br>



<div class="container-lg">
  
    <h2 style="color: rgb(0, 0, 0); font-family: Georgia, 'Times New Roman', Times, serif; "> Credit / Debit Monthly Report</h2>

    <form class="row g-3" method="post">
      {% csrf_token %}
      <div class="col-auto">
        <label class="form-control-plaintext"> Filter by Year</label>
      </div>
      <div class="col-auto">
        <label for="inputYear" class="visually-hidden">Year</label>
        <input type="search" class="form-control" id="inputYear" name="yearFilter" required placeholder="Year">
      </div>
      <div class="col-auto">
        <button type="submit" class="btn btn-primary mb-3">Search</button>
      </div>
    </form>
<table style="border-style: dotted;" class="table table-bordered">
    <thead>
      <tr>
        <th  scope="col" class="text-center" >Year</th>
        <th scope="col" class="text-center">Month</th>
        <th scope="col" class="text-center">Total Credit</th>
        <th scope="col" class="text-center">Total Debit</th>
        <th scope="col" class="text-center">Comments</th>
      </tr>
    </thead>
    <tbody>
      {% for x in projectListQuery %}
      <tr >   
        <td align ="center" >{{x.year|date:"Y"}}</td>
        <td>{{x.month|date:"F"}}</td>
        <td align ="right">{{x.TCredit|intcomma}}</td>
        <td align ="right">{{x.TDebit|intcomma}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>



{% endblock %}

OmarCrm/CRM/templates/CRM/NewComment.html
{% include 'CRM/base.html' %}
{% include 'CRM/navbar.html' %}


{% block content %}

<div class="container-lg">
    <h4 style="color:rgb(98, 157, 224);">All Comments</h4>
<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Comment Date</th>
        <th scope="col">Comment</th>
        <th scope="col">Created By</th>
      </tr>
    </thead>
    <tbody>
      <tr>
          {% for x in CommentList %}
        <th scope="row" ><a href="/customerProfile/{{x.commentId}}">{{x.commentId}}</a></th>
        <td>{{x.commentDate|date:'d-M-Y - H:i A'}}</td>
        <td>{{x.comment}}</td>
        <td>{{x.createdBy}}</td>

      </tr>
      {% endfor %}
    </tbody>
  </table>



<div style="background-color: rgb(148, 167, 242);" class="container form-control">



        <H3 style="color:rgb(255, 255, 255);">Add New Comment</H3>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary btn-lg btn-block">Save</button>

        </form>
</div>
</div>

{% endblock %}

OmarCrm/CRM/templates/CRM/NewPayment.html
{% include 'CRM/base.html' %}
{% include 'CRM/navbar.html' %}

{% block content %}

<br>

<div class="col-md-12 container form-control" style="border-radius: 10%;">
        <br>
        {% if request.path == '/NewPayment' %}
        <h2 class="container center" style="">Create New Payment</h2>
        
        {% else %}
        <h2>Update Payment </h2>
        {% endif %}
        <br>
        <form method="post">
        {% csrf_token %}

        {{ form.as_p }}
        <input style="border-radius: 10ch;" class="btn btn-primary form-control" type="submit" value="Save The Payment">
<br>
<br>
        

        </form>
</div>


{% endblock %}

OmarCrm/CRM/templates/CRM/NewProject.html
{% include 'CRM/base.html' %}
{% include 'CRM/navbar.html' %}



{% block content %}

<br>



<div class="col-md-6 container-sm form-control">
        {% if request.path == '/NewProject' %}
        <h1>Create New Project  </h1>
        
        {% else %}
        <h1>Update Project Info </h1>
        {% endif %}
        <br>
        <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <input class="btn btn-primary" type="submit" value="Save">

        </form>
</div>


{% endblock %}

OmarCrm/CRM/templates/CRM/ZTest.html
{% include 'CRM/base.html' %}
{% include 'CRM/navbar.html' %}
{% load humanize %}
{% block content %}

<div class="container">
{% for x in Q1 %}
<li>{{x}}</li>
{% endfor %}
</div>

{% endblock %}

OmarCrm/CRM/templates/CRM/ZTestView.html
{% include 'CRM/base.html' %}
{% include 'CRM/navbar.html' %}



{% block content %}

<br>



<div class="col-md-6 container-sm form-control">
        <H2>Create New Customer</H2>
        <br>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Save">

        </form>
</div>


{% endblock %}

OmarCrm/CRM/templates/CRM/customerList.html
{% include 'CRM/base.html' %}
{% include 'CRM/navbar.html' %}

{% block content %}

<br>
<div class="container-lg">
    <h2>Active Customer List</h2>
<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Customer ID</th>
        <th scope="col">Customer Name</th>
        <th scope="col">Country</th>
        <th scope="col">Mobile Number</th>
        <th scope="col">User Login</th>
        <th scope="col">Active</th>
        <th scope="col">Created By</th>
        <th scope="col">Update</th>
      </tr>
    </thead>
    <tbody>
      <tr>
          {% for x in customerListQuery %}
        <th scope="row" ><a href="/customerProfile/{{x.customerId}}">{{x.customerId}}</a></th>
        <td>{{x.customerName}}</td>
        <td>{{x.country}}</td>
        <td>{{x.mobileNumber}}</td>
        <td>{{x.userLogin}}</td>
        {% if x.active == True %} <td>Yes</td> {% else %} <td>No</td> {% endif %}
        <td>{{x.createdBy}}</td>
        <td><button class="btn btn-outline-success" type="submit" onclick="location.href='{% url 'CRM:updateCustomerProfile' x.customerId %}'">edit</button></td>

      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>


{%  endblock %}

OmarCrm/CRM/templates/CRM/financeCustomerBalance.html
{% include 'CRM/base.html' %}
{% include 'CRM/navbar.html' %}

{% load humanize %}

{% block content %}

{{ request.path_info}}

<br>
<div class="container-lg">
    <h2 style="color: blue;">Statment of Account : {{Soa_Customer.0.customerName}} </h2>
    <br>
<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Customer ID</th>
        <th scope="col">Customer Name</th>
        <th scope="col">Credit</th>
        <th scope="col">Debit</th>
        <th scope="col">Open Balance</th>
      </tr>
    </thead>
    <tbody>
      <tr>
          {% for x in Soa_Customer %}
        <th scope="row" ><a href="/customerProfile/{{x.customerId}}">{{x.customerId}}</a></th>
        <td>{{x.customerName}}</td>
        <td>{{x.totalCredit}}</td>
        <td >{{x.totalDebit}}</td>
        <td>{{x.openBalance}}</td>


      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<br>
<div class="container-lg">
    <h2 style="color: blue;">Detailed Account</h2>
    <br>
<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Customer ID</th>
        <th scope="col">Customer Name</th>
        <th scope="col">transactionDate</th>
        <th scope="col">paymenttype</th>
        <th scope="col">paymentRef</th>
        <th scope="col">type</th>
        <th scope="col">credit</th>
        <th scope="col">debit</th>
      </tr>
    </thead>
    <tbody>
      <tr>
          {% for x in SoaDtl_Customer %}
        <th scope="row" ><a href="/customerProfile/{{x.customerId}}">{{x.customerId}}</a></th>
        <td>{{x.customerName}}</td>
        <td>{{x.transactionDate}}</td>
        <td>{{x.paymenttype}}</td>
        <td>{{x.paymentRef}}</td>
        <td>{{x.type}}</td>
        <td>{{x.credit}} {{x.Currency}}</td>
        <td>{{x.debit}} {{x.Currency}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

OmarCrm/CRM/templates/CRM/financeOpenBalance.html
{% include 'CRM/base.html' %}
{% include 'CRM/navbar.html' %}

{% load humanize %}

{% block content %}

{{ request.path_info}}

{% if request.path_info == '/financeOpenBalance' %}
<br>
<div class="container-lg">
    <h2>Open Balance List</h2>
<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Customer ID</th>
        <th scope="col">Customer Name</th>
        <th scope="col">Credit</th>
        <th scope="col">Debit</th>
        <th scope="col">Open Balance</th>
      </tr>
    </thead>
    <tbody>
      <tr>
          {% for x in SOA_OpenBalance %}
        <th scope="row" ><a href="/customerProfile/{{x.customerId}}">{{x.customerId}}</a></th>
        <td>{{x.customerName}}</td>
        <td>{{x.totalCredit}}</td>
        <td >{{x.totalDebit}}</td>
        <td>{{x.openBalance}}</td>


      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% else %}
<br>
<div class="container-lg">
    <h2>Closed Balance List</h2>
<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Customer ID</th>
        <th scope="col">Customer Name</th>
        <th scope="col">Credit</th>
        <th scope="col">Debit</th>
        <th scope="col">Open Balance</th>
      </tr>
    </thead>
    <tbody>
      <tr>
          {% for x in SOA_ClosedBalance %}
        <th scope="row" ><a href="/customerProfile/{{x.customerId}}">{{x.customerId}}</a></th>
        <td>{{x.customerName}}</td>
        <td>{{x.totalCredit}}</td>
        <td >{{x.totalDebit}}</td>
        <td>{{x.openBalance}}</td>


      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endif %}
{% endblock %}

OmarCrm/CRM/templates/CRM/index.html
{% include 'CRM/base.html' %}
{% include 'CRM/navbar.html' %}

{% block content %}
{% if user.is_authenticated %}

<h1>welcome {{user.get_username}}</h1>
<li><a href="{% url 'CRM:customerList' %}">customerList</a></li>

<a href="{% url 'logout'%}">logout</a>
{% else %}


<a href="{% url 'login'%}">login</a>

{% endif %}



{% endblock %}

OmarCrm/CRM/templates/CRM/paymentsmodel_confirm_delete.html
{% include 'CRM/base.html' %}
{% include 'CRM/navbar.html' %}

{% block content %}
<br>
<div class="container">
<h2>are you sure want to delete ? </h2>
<form method="post" class="from-control">
    {% csrf_token %}
<input class="btn-lg btn-danger btn-block" type="submit" value="Yes">
</form>
<button class="btn-lg btn btn-outline-secondary btn-block" onclick="location.href='{% url 'CRM:PaymentHitoryList'%}'">cancel</a></button>
</div>
{%  endblock %}

OmarCrm/CRM/templates/CRM/signUp.html
{% include 'CRM/base.html' %}
{% include 'CRM/navbar.html' %}



{% block content %}

<br>



<div class="col-md-6 container-sm form-control">
        <H2>Create New Customer</H2>
        <br>
        <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <input class="btn btn-primary" type="submit" value="Save">

        </form>
</div>


{% endblock %}